language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
  - elasticsearch

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  include:
    - python: 3.6

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda update conda --yes
  - conda config --add channels conda-forge

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --file requirements.txt
  - pip install .
  - git clean -xfd

script:
  - set -e
  - conda install pytest coverage codecov
  # make sure the sqlite file exists to avoid race conditions
  - python -c "from bluesky.utils import get_history; get_history()"
  - coverage run run_tests.py
  - coverage report -m
  - codecov
#  - conda install --yes --file requirements/docs.txt
#  - cd docs
#  - make html
#  - cd ..
#  - doctr deploy . --built-docs ./docs/_build/html;

after_script:
  - set +e
  - flake8 .
