language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

services:
  - mongodb
  - elasticsearch

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  include:
    - python: 3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash ./miniconda.sh -b -p ~/mc
  - source ~/mc/bin/activate base
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda update conda --yes
  - conda config --add channels conda-forge

install:
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --file requirements.txt
  - pip install .
  - git clean -xfd

before_script:
  - conda install pytest coverage codecov flake8
  # use matplotlib backend that does not need DISPLAY
  - export MPLBACKEND=agg
  # make sure the sqlite file exists to avoid race conditions
  - python -c "from bluesky.utils import get_history; get_history()"

script:
  - coverage run --source databroker_elasticsearch,src/tests run_tests.py

after_success:
  - coverage report -m
  - codecov
#  - conda install --yes --file requirements/docs.txt
#  - cd docs
#  - make html
#  - cd ..
#  - doctr deploy . --built-docs ./docs/_build/html;

after_script:
  - flake8 .
